global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]


remote_write:
- url: http://victoria_metrics:8428/api/v1/write
  queue_config:
    max_samples_per_send: 10000
    capacity: 20000
    max_shards: 30